Repository programacion-6/Opcion1LosCules, pull requests merged in 2024-08, with the labels that each got.

#28 Refactor UML
  src/UML/Entities.puml
  src/UML/LibrarySystem.puml
  src/UML/Managers.puml
  src/UML/Search.puml
Labels: UML

#29 Revert "Refactor UML" from develop
  src/UML/Entities.puml
  src/UML/LibrarySystem.puml
  src/UML/Managers.puml
  src/UML/Search.puml
Labels: revert

#30 Refactor: UML modifications to release
  src/UML/BookManagement.puml
  src/UML/Entities.puml
  src/UML/LibrarySystem.puml
  src/UML/Managers.puml
  src/UML/PatronManagement.puml
  src/UML/Search.puml
Labels: UML

#31 Feature/ID-32/implement-ci
  .github/workflows/CI.yml
Labels: ci

#32 chore: implement gitignore
  .gitignore
Labels: chore
